export enum UserEnum {
  USER_NOT_EXISTS = 'USER_NOT_EXISTS',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USER_DOES_NOT_HAVE_THIS_ROLE = 'USER_DOES_NOT_HAVE_THIS_ROLE',
  USER_MUST_ATLEAST_HAS_ONE_ROLE = 'USER_MUST_ATLEAST_HAS_ONE_ROLE',
}
